[versions]
jjwt = "0.12.6"
postgresql = "42.6.0"
springBoot = "3.3.5"

[libraries]
springBootWeb = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
springBootSecurity = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springBoot" }
jjwtApi = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwtImpl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwtJackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
postgresqlDriver = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
