[versions]
springBoot = "3.3.5"
dependencyManagement = "1.1.7"
java = "1.10"

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
dependencyManagement = { id = "io.spring.dependency-management", version.ref = "dependencyManagement" }
java = { id = "java", version.ref = "java" }  # optional standard Java plugin
